#!/usr/bin/env bash

# requires bash 4.2 or later

[[ -v CONFIGURATION_COMPLETED ]] && echo "Using preloaded configuration" && { return || exit ; }

# demo configuration
DEMO_INTERACTIVE=false
DEMO_INTERACTIVE_PROMPT="Press enter to continue"
DEMO_INTERACTIVE_PROMPT_TIMEOUT_SECONDS=10

OPENSHIFT_CLUSTER_VERIFY_OPERATIONAL_STATUS=false
OPENSHIFT_PRIMARY_AUTH_METHODS=(password kerberos token cert github giventoken)
OPENSHIFT_OUTPUT_FORMATS=(json yaml)

[[ -v ${DEMO_TARGET_OPENSHIFT_INSTANCES} ]] || DEMO_TARGET_OPENSHIFT_INSTANCES=(local rhsademo rhtps-io fortnebula itpaas nsabine-vrtx hattrick1)

# By default, Target RHSADEMO
: ${DEMO_TARGET_OPENSHIFT_INSTANCE:=${DEMO_TARGET_OPENSHIFT_INSTANCES[1]}}

: ${OPENSHIFT_PRIMARY_AUTH_METHODS?"Missing configuration for available auth methods"}
: ${OPENSHIFT_OUTPUT_FORMATS?"Missing configuration for available output formats"}
: ${DEMO_TARGET_OPENSHIFT_INSTANCES?"Missing configuration for available demo targets"}
: ${DEMO_TARGET_OPENSHIFT_INSTANCE?"Missing configuration for designated demo target"}

CONFIGURATION_DEMO_TARGET_SCRIPT=config-demo-target-${DEMO_TARGET_OPENSHIFT_INSTANCE}.sh
. ${CONFIGURATION_DEMO_TARGET_SCRIPT} || { echo "FAILED: Could not run demo target configuration script ${CONFIGURATION_DEMO_TARGET_SCRIPT}" && exit 1 ; }

echo -n "Verifying minimum configuration options..."
: ${OPENSHIFT_DOMAIN_DEFAULT?"OPENSHIFT_DOMAIN_DEFAULT must be provided by ${CONFIGURATION_DEMO_TARGET_SCRIPT}"}
: ${OPENSHIFT_MASTER_PRIMARY_DEFAULT?"OPENSHIFT_MASTER_PRIMARY_DEFAULT must be provided by ${CONFIGURATION_DEMO_TARGET_SCRIPT}"}
: ${OPENSHIFT_MASTER_PRIMARY_DEFAULT_PORT_HTTPS?"OPENSHIFT_MASTER_PRIMARY_DEFAULT_PORT_HTTPS must be provided by ${CONFIGURATION_DEMO_TARGET_SCRIPT}"}
: ${OPENSHIFT_APPS_PRIMARY_DEFAULT?"OPENSHIFT_APPS_PRIMARY_DEFAULT must be provided by ${CONFIGURATION_DEMO_TARGET_SCRIPT}"}
: ${OPENSHIFT_LOGGING_PRIMARY_DEFAULT?"OPENSHIFT_LOGGING_PRIMARY_DEFAULT must be provided by ${CONFIGURATION_DEMO_TARGET_SCRIPT}"}
: ${OPENSHIFT_PROXY_AUTH_PRIMARY_DEFAULT?"OPENSHIFT_PROXY_AUTH_PRIMARY_DEFAULT must be provided by ${CONFIGURATION_DEMO_TARGET_SCRIPT}"}
: ${OPENSHIFT_AUTH_METHOD_PRIMARY_DEFAULT?"OPENSHIFT_AUTH_METHOD_PRIMARY_DEFAULT must be provided by ${CONFIGURATION_DEMO_TARGET_SCRIPT}"}
: ${OPENSHIFT_USER_PRIMARY_DEFAULT?"OPENSHIFT_USER_PRIMARY_DEFAULT must be provided by ${CONFIGURATION_DEMO_TARGET_SCRIPT}"}
: ${OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT?"OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT must be provided by ${CONFIGURATION_DEMO_TARGET_SCRIPT}"}
: ${OPENSHIFT_PROJECT_PRIMARY_DEFAULT?"OPENSHIFT_PROJECT_PRIMARY_DEFAULT must be provided by ${CONFIGURATION_DEMO_TARGET_SCRIPT}"}
: ${OPENSHIFT_APPLICATION_NAME_DEFAULT?"OPENSHIFT_APPLICATION_NAME_DEFAULT must be provided by ${CONFIGURATION_DEMO_TARGET_SCRIPT}"}
: ${OPENSHIFT_OUTPUT_FORMAT_DEFAULT?"OPENSHIFT_OUTPUT_FORMAT_DEFAULT must be provided by ${CONFIGURATION_DEMO_TARGET_SCRIPT}"}
echo "OK"

if [ "$CONFIGURATION_DISPLAY" != "false" ]; then
	echo "Configuration_______________________________________________"
	echo "	DEMO_INTERACTIVE                        = ${DEMO_INTERACTIVE}"
	echo "	DEMO_INTERACTIVE_PROMPT                 = ${DEMO_INTERACTIVE_PROMPT}"
	echo "	DEMO_INTERACTIVE_PROMPT_TIMEOUT_SECONDS = ${DEMO_INTERACTIVE_PROMPT_TIMEOUT_SECONDS}"
	echo "	DEMO_TARGET_OPENSHIFT_INSTANCE          = ${DEMO_TARGET_OPENSHIFT_INSTANCE}"
	echo "	OPENSHIFT_DOMAIN_DEFAULT                = ${OPENSHIFT_DOMAIN_DEFAULT}"
	echo "	OPENSHIFT_MASTER_PRIMARY_DEFAULT        = ${OPENSHIFT_MASTER_PRIMARY_DEFAULT}"
	echo "	OPENSHIFT_APPS_PRIMARY_DEFAULT          = ${OPENSHIFT_APPS_PRIMARY_DEFAULT}"
	echo "	OPENSHIFT_LOGGING_PRIMARY_DEFAULT       = ${OPENSHIFT_LOGGING_PRIMARY_DEFAULT}"
	echo "	OPENSHIFT_PROXY_AUTH_PRIMARY_DEFAULT    = ${OPENSHIFT_PROXY_AUTH_PRIMARY_DEFAULT}"
	echo "	OPENSHIFT_AUTH_METHOD_PRIMARY_DEFAULT   = ${OPENSHIFT_AUTH_METHOD_PRIMARY_DEFAULT}"
	echo "	OPENSHIFT_USER_PRIMARY_DEFAULT          = ${OPENSHIFT_USER_PRIMARY_DEFAULT}"
	echo "	OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT = `echo ${OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT} | md5sum` (obfuscated)"
	echo "	OPENSHIFT_PROJECT_PRIMARY_DEFAULT       = ${OPENSHIFT_PROJECT_PRIMARY_DEFAULT}"
	echo "	OPENSHIFT_APPLICATION_NAME_DEFAULT      = ${OPENSHIFT_APPLICATION_NAME_DEFAULT}"
	echo "	OPENSHIFT_OUTPUT_FORMAT_DEFAULT         = ${OPENSHIFT_OUTPUT_FORMAT_DEFAULT}"
	echo "____________________________________________________________"
fi

CONFIGURATION_COMPLETED=true
